---
abstract: 'Simple implementation to determine file type'
author:
  - 'David Moreno <damog@damog.net>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
  File::Temp: 0
  File::Spec: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
generated_by: 'hand'
license: perl_5
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-MimeInfo-Simple
no_index:
  directory:
    - t
requires:
  YAML::Syck: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/damog/File-MimeInfo-Simple/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/damog/File-MimeInfo-Simple.git
version: '0.8'
